{{ if .Values.secret.nexusAdmin.generatorJob.enabled }}
# TODO: migrate to umbrella Helm Chart
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-generator-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-generator-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-generator-rb
subjects:
  - kind: ServiceAccount
    name: secret-generator-sa
roleRef:
  kind: Role
  name: secret-generator-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: generate-secrets
  labels:
{{ include "nexus.labels" . | nindent 4 }}
  {{- if .Values.nexus.extraLabels }}
    {{- with .Values.nexus.extraLabels }}
      {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: secret-generator-sa
      securityContext:
        runAsNonRoot: true
      containers:
        - name: secret-generator
          {{ with .Values.secret.nexusAdmin.generatorJob.image }}
          image: "{{ .repository }}:{{ .tag }}"
          {{ end }}
          securityContext:
            capabilities:
              drop:
                - ALL
          command:
            - /bin/bash
            - -c
            - |
              SECRET_NAME="{{ template "nexus.name" . }}-adminsecret"
              if kubectl get secret ${SECRET_NAME} > /dev/null 2>&1; then
                echo "Secret already exists, skipping generation."
                exit 0
              fi
              PASSWORD=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 32)
              kubectl create secret generic ${SECRET_NAME} \
                --from-literal=password="${PASSWORD}"
              echo "Secret created."
          startupProbe:
            exec:
              command:
                - ls
                - /usr/local/bin/kubectl
            initialDelaySeconds: 1
            periodSeconds: 30
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            exec:
              command:
                - ls
                - /usr/local/bin/kubectl
            initialDelaySeconds: 3
            periodSeconds: 30
            timeoutSeconds: 2
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - ls
                - /usr/local/bin/kubectl
            initialDelaySeconds: 1
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
      restartPolicy: OnFailure

{{ end }}